# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - '**'       # Run the workflow when pushing to the main branch
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    
    - name: Build
      run: dotnet build -c Release
    
    - name: Archive SharpEngine Nuget Package
      uses: actions/upload-artifact@v3
      with:
        name: Nuget
        path: SharpEngine/bin/Release/SharpEngine.*.nupkg

  validate_nuget:
    runs-on: ubuntu-latest
    needs: [ create_nuget ]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - uses: actions/download-artifact@v3
        with:
          name: Nuget
          path: SharpEngine/bin/Release/SharpEngine.*.nupkg

      - name: Install nuget validator
        run: dotnet tool update Meziantou.Framework.NuGetPackageValidation.Tool --global
        
      - name: Validate package
        run: meziantou.validate-nuget-package (Get-ChildItem "SharpEngine/bin/Release/SharpEngine.*.nupkg")

  run_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Run tests
      run: dotnet test --configuration Release

  deploy:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ validate_nuget, run_test ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Nuget
          path: SharpEngine/bin/Release/SharpEngine.*.nupkg

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Publish NuGet package
        run: dotnet nuget push "SharpEngine/bin/Release/SharpEngine.*.nupkg" --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
    
